name: weathertechtita
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  intl: ^0.17.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/techtitans.png"
  adaptive_icon_background: "#29222F"

flutter:
  uses-material-design: true
